### ISSUE TITLE
What is training input data format?

### ISSUE THREAD

**Issue by yzhang-github-pub** [lightonai/RITA#10]
Dear Author,

I am fine-tuning your pretrained RITA with a protein family data, using run_clm.py script @ huggingface. I tried this format where seq1 & seq2 are protein sequences 1 & 2 without white space:

seq1
<|endoftext|>
seq2
<|endoftext|>
...

and also this format:
seq1
seq2
...

Training seemed to be successful. However, sequences generated by the fine tuned model contain a lot of '<unk>' tokens.

Please advise. Thanks.

**Comment by DanielHesslow** [comment]
I'm not particularly familiar with the huggingface code base, and I do not currently have the time to read up one the specifics. 

The format used during training is:
```
seq1
<EOS>
seq2
<EOS>
...
```

The issue does however seem unrelated to the input format, the version without `<EOS>` should also work fine. It outputting `"` Is strange since this token is not part of our vocabulary, I'd make sure that you train using our tokenizer: 
```python
tokenizer = AutoTokenizer.from_pretrained("lightonai/RITA_s")
```

**Comment by pzhang84** [comment]
Hi @DanielHesslow, Could you please advise what tokenizer you used for training RITA, and what is the vocabulary size? Thanks!

**Comment by DanielHesslow** [comment]
`tokenizer = AutoTokenizer.from_pretrained("lightonai/RITA_s")`
Is indeed the correct tokenizer. the vocab size is 26.
